import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GithubIcon } from "lucide-react";
import Link from "next/link";
import { Button } from "./_components/ui/button2";

const geistSans = localFont({
	src: "./_fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./_fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="top-0 left-0 fixed bg-white border-b w-full">
					<div className="mx-auto px-4 sm:px-6 lg:px-8 container">
						<div className="flex justify-between items-center h-16">
							<div className="flex items-center">
								<Link href="/" className="flex items-center">
									<GithubIcon className="w-8 h-8 text-primary" />
									<span className="ml-2 font-bold text-primary text-xl">
										GitHub Profile
									</span>
								</Link>
							</div>
							<nav>
								<Button asChild variant="ghost">
									<Link href="/">Home</Link>
								</Button>
							</nav>
						</div>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
